[package]
name = "credential-store"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-only"

[dependencies]
async-trait.workspace = true
keyring.workspace = true
serde = { workspace = true, features = ["derive"] }
thiserror.workspace = true
tokio = { workspace = true, features = ["rt", "sync"] }
