use std::{
    fs::File,
    io::Write,
    path::{Path, PathBuf},
};

use serde::Serialize;
use zip::{ZipWriter, write::SimpleFileOptions};

const MAX_LOG_BYTES: u64 = 8 * 1024 * 1024;
const SENSITIVE_KEYS: [&str; 12] = [
    "token",
    "access_token",
    "auth",
    "authkey",
    "api_key",
    "apikey",
    "key",
    "password",
    "pass",
    "pin",
    "signature",
    "credential",
];

#[derive(Clone, Debug, Eq, PartialEq, thiserror::Error)]
pub enum DiagnosticError {
    #[error("diagnostic file operation failed")]
    Filesystem,
    #[error("diagnostic serialization failed")]
    Serialization,
}

#[derive(Serialize)]
struct DiagnosticSummary {
    application: &'static str,
    version: &'static str,
    operating_system: &'static str,
    architecture: &'static str,
    generated_at: i64,
    note: &'static str,
}

pub async fn create_redacted_zip(destination: &Path) -> Result<PathBuf, DiagnosticError> {
    let destination = destination.to_path_buf();
    let destination_for_zip = destination.clone();
    let logs_dir = crate::paths::get().logs().to_path_buf();
    tokio::task::spawn_blocking(move || create_zip(&destination_for_zip, &logs_dir))
        .await
        .map_err(|_| DiagnosticError::Filesystem)??;
    Ok(destination)
}

pub fn prefilled_issue_url(summary: &str) -> String {
    let body = format!(
        "### Problem\n{}\n\n### Diagnostics\nAttach the redacted diagnostic ZIP generated by Stremio Native.",
        redact_text(summary)
    );
    let mut url = url::Url::parse("https://github.com/Zaarrg/stremio-native/issues/new")
        .expect("static issue URL must be valid");
    url.query_pairs_mut()
        .append_pair("template", "bug_report.yml")
        .append_pair("body", &body);
    url.to_string()
}

pub fn redact_text(input: &str) -> String {
    let mut output = String::with_capacity(input.len());
    for line in input.lines() {
        let trimmed = line.trim_start();
        if trimmed
            .get(..14)
            .is_some_and(|prefix| prefix.eq_ignore_ascii_case("authorization:"))
        {
            output.push_str("Authorization: [REDACTED]\n");
            continue;
        }
        for token in line.split_inclusive(char::is_whitespace) {
            let bare = token.trim_end();
            let whitespace = &token[bare.len()..];
            if let Ok(mut url) = url::Url::parse(bare) {
                let pairs = url
                    .query_pairs()
                    .map(|(key, value)| {
                        let value = if is_sensitive_key(&key) {
                            "[REDACTED]".to_owned()
                        } else {
                            value.into_owned()
                        };
                        (key.into_owned(), value)
                    })
                    .collect::<Vec<_>>();
                if !pairs.is_empty() {
                    url.query_pairs_mut().clear().extend_pairs(pairs);
                }
                output.push_str(url.as_str());
            } else if let Some((key, _value)) = bare.split_once('=') {
                if is_sensitive_key(key) {
                    output.push_str(key);
                    output.push_str("=[REDACTED]");
                } else {
                    output.push_str(bare);
                }
            } else if let Some((key, _value)) = bare.split_once(':') {
                if is_sensitive_key(key.trim_matches(['"', '\'', '{', ','])) {
                    output.push_str(key);
                    output.push_str(":[REDACTED]");
                } else {
                    output.push_str(bare);
                }
            } else {
                output.push_str(bare);
            }
            output.push_str(whitespace);
        }
        output.push('\n');
    }
    output
}

fn create_zip(destination: &Path, logs_dir: &Path) -> Result<(), DiagnosticError> {
    if let Some(parent) = destination.parent() {
        std::fs::create_dir_all(parent).map_err(|_| DiagnosticError::Filesystem)?;
    }
    let temporary = destination.with_extension("diagnostics.tmp");
    let file = File::create(&temporary).map_err(|_| DiagnosticError::Filesystem)?;
    let mut archive = ZipWriter::new(file);
    let options = SimpleFileOptions::default()
        .compression_method(zip::CompressionMethod::Deflated)
        .unix_permissions(0o600);
    let summary = serde_json::to_vec_pretty(&DiagnosticSummary {
        application: "Stremio Native",
        version: env!("CARGO_PKG_VERSION"),
        operating_system: std::env::consts::OS,
        architecture: std::env::consts::ARCH,
        generated_at: chrono::Utc::now().timestamp(),
        note: "Secrets and credential-bearing URL query values are redacted.",
    })
    .map_err(|_| DiagnosticError::Serialization)?;
    archive
        .start_file("summary.json", options)
        .map_err(|_| DiagnosticError::Filesystem)?;
    archive
        .write_all(&summary)
        .map_err(|_| DiagnosticError::Filesystem)?;

    let mut log_files = std::fs::read_dir(logs_dir)
        .into_iter()
        .flatten()
        .flatten()
        .filter_map(|entry| {
            let metadata = entry.metadata().ok()?;
            (metadata.is_file() && metadata.len() <= MAX_LOG_BYTES)
                .then_some((entry.path(), metadata.modified().ok()))
        })
        .collect::<Vec<_>>();
    log_files.sort_by_key(|(_, modified)| *modified);
    for (index, (path, _)) in log_files.into_iter().rev().take(5).enumerate() {
        let contents = std::fs::read_to_string(path).map_err(|_| DiagnosticError::Filesystem)?;
        archive
            .start_file(format!("logs/log-{}.txt", index + 1), options)
            .map_err(|_| DiagnosticError::Filesystem)?;
        archive
            .write_all(redact_text(&contents).as_bytes())
            .map_err(|_| DiagnosticError::Filesystem)?;
    }
    archive.finish().map_err(|_| DiagnosticError::Filesystem)?;
    std::fs::rename(&temporary, destination).map_err(|_| DiagnosticError::Filesystem)
}

fn is_sensitive_key(key: &str) -> bool {
    let normalized = key
        .trim_matches(|character: char| !character.is_ascii_alphanumeric() && character != '_')
        .to_ascii_lowercase();
    SENSITIVE_KEYS.iter().any(|sensitive| {
        normalized == *sensitive
            || normalized.ends_with(&format!("_{sensitive}"))
            || normalized.ends_with(&format!("-{sensitive}"))
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn redacts_headers_queries_and_key_value_tokens() {
        let canary = "canary-super-secret";
        let input = format!(
            "Authorization: Bearer {canary}\nhttps://example.test/video?token={canary}&id=42\napi_key={canary}"
        );
        let redacted = redact_text(&input);
        assert!(!redacted.contains(canary));
        assert!(redacted.contains("id=42"));
    }

    #[test]
    fn issue_links_never_include_raw_secret_queries() {
        let url = prefilled_issue_url("failed https://example.test/?password=canary");
        assert!(!url.contains("canary"));
    }
}
